== Command line option

=== Runtime

java -jar atbash-runtime.jar <options>

*-r|--root*: Location of 'domain' directory, by default current directory.

*-n|--configname*: Configuration name within the domain, by default `default`.

*-v|--verbose*: When active, more messages are shown in the log.  This can be enforced 'permanent' by putting `be.atbash.runtime.level=ALL` in the logging configuration.

*--watcher*:  Defines the type of the diagnostics, valid values are  +
`MINIMAL`: (default) only the events from the Core module are sent to JFR.  +
`OFF`: JFR and JMX are disabled  +
`JFR`: Events are send to JFR system and Recording is started which is dump to file at JVM exit.  +
`JMX`: Some data is available within the JMX system.  +
`ALL`: Combination of `JFR` and `JMX`

*-p|--profile*:  The name of the active profile. The Profile defines a set of modules that are started.  When not specified, the profile id `default`. Also `domain` is supported. +

*-m|--modules*: Change the modules that are active.  the option is a comma separated ist list of _module definitions_.  +
A module definition  consist of the module name that is optionally prepended by `+` or `-` or no action indicator. +
The final list of modules that are used is determined by the profile and then changes are done as following

No action, the modules defined in the profile are replaced by these modules.  +
`+` The module is added to the current list of modules  +
`-` The module is removed from the current list of modules

The mandatory modules _Config_  and _Logging_  are always added to the list.

The `--modules` option is an expert setting and using it incorrectly can result in a failure to run your application.

*--stateless*:  No configuration information is stored on disk for future runs.  Ideal for creating stateless containers in combination with `--no-logToFile`.

*--logToConsole*: Send all logging to the console.  This overrules the value in the logging configuration file (TBC)

*--no-logToFile*: Does not send logging to the file.  This overrules the value in the logging configuration file (TBC)

zero, one or more WAR files can be added to the command line that needs to be deployed. Also the applications that are already 'deployed' within the configuration are started.

The exit status of the process it

- 0: normal exit
- -1: Incorrect commandline options specified
- -2: Runtime failed to start due to some error.

*-c|--configfile* Defines the configuration file with commands that needs to be executed. after start up of the runtime but before the applications are deployed.
The file can contain comments when the line starts with `#`. Otherwise the line need to contain a valid command as specified in the next section _CLI_

=== CLI

java -jar atbash-cli.jar <command> <options>

==== create-config

Create a configuration within the domain.

xx To be documented xx

==== Options for all remote commands

-h | --host (default - localhost): Host name or IP address of the machine running the Atbash runtime in Domain mode.

-p | --port (default - 8080): Port number assigned the process running the Atbash runtime in Domain mode


-f | --format (default - TEXT): Format output of the Remote CLI commands.  Support values are TEXT and JSON.

==== status (remote)

Returns the status and information of the runtime with as output.

version - version number of the runtime.
modules - the active modules of the runtime.
uptime - The time the runtime is already running.

=== deploy (remote)

Deploys the application on the runtime, and optionally define the context root.

`deploy <file>`

`deploy --contextroot <root> <file>`

`deploy --contextroot <root1,root2> <file1> <file2>`

Altough deploying multiple applications is supported, it is not recommended as the outcome might not be clear in case one of the deployments fails.

=== list-applications (remote)

List all applications running on the runtime.

=== undeploy (remote)

Undeploy an application

`undeploy <name>`

=== set (remote)

Set configuration parameters for modules. The parameters must be in the form of <module>.<key>=value.  Multiple parameters can be specified one the same set command (space separated)

`set mp-config.validation.disable=true`