== Command line option

=== Runtime

java -jar atbash-runtime.jar <options>

-r|--root: Location of 'domain' directory, by default current directory.

-n|--configname: Configuration name within the domain, by default `default`.

-v|--verbose: Are all log messages shown on the console.

--watcher:  Defines the type of the diagnostics, valid values are  +
`MINIMAL`: (default) only the events from the Core module are sent to JFR.  +
`OFF`: JFR and JMX are disabled  +
`JFR`: Events are send to JFR system and Recording is started which is dump to file at JVM exit.  +
`JMX`: Some data is available within the JMX system.  +
`ALL`: Combination of `JFR` and `JMX`

zero, one or more WAR files can be added to the command line that needs to be deployd. Also the applications that are already 'deployed' within the configuration are started.

=== CLI

java -jar atbash-runtime.jar <command> <options>

==== create-config

Create a configuration within the domain.

xx To be documented xx

==== Options for all remote commands

-h | --host (default - localhost): Host name or IP address of the machine running the Atbash runtime in Domain mode.

-p | --port (default - 8080): Port number assigned the process running the Atbash runtime in Domain mode


-f | --format (default - TEXT): Format output of the Remote CLI commands.  Support values are TEXT and JSON.

==== status (remote)

Returns the status and information of the runtime with as output.

version - version number of the runtime.
modules - the active modules of the runtime.
uptime - The time the runtime is already running.

=== deploy (remote)

Deploys the application on the runtime, and optionally define the context root.

`deploy <file>`

`deploy --contextroot <root> <file>`

`deploy --contextroot <root1,root2> <file1> <file2>`

=== list-applications (remote)

List all applications running on the runtime.

=== undeploy (remote)

Undeploy an application

`undeploy <name>`