=== Docker

A Docker image is available to run the Atbash Runtime containerized.  It is based on JDK 11 and has several environment variables to configure its configuration.  The Runtime runs with the stateless option, no files are created unless one configuration file in the temporary folder.

=== Basic usage

[source]
----
FROM runtime-main:0.4
COPY myservice.war $DEPLOYMENT_DIR
----

The $DEPLOYMENT_DIR is a variable that is also passed to the start up command as the directory that is scanned for WAR applications that needs to be deployed.

=== Environment variables

These are the environment variables that can be used to modify the configuration:

- *MEM_MAX_RAM_PERCENTAGE* (default "70.0"): The amount of the Java Heap within the container as a percentage of the total memory assigned to the container.
- *MEM_XSS* (default 512k) Value of the stack size.
- *JVM_ARGS*: Other JVM Arguments.
- *ATBASH_ARGS*: Options for the Atbash Runtime.
- *STATELESS*: Has by default the value _true_ which results in the addition of the options `--stateless --no-logToFile` to the options passed to Atbash Runtime.  When you define another value for the environment variable, you can have the non stateless behaviour.

This is the command that starts the instance.

[source]
----
exec java -XX:MaxRAMPercentage=${MEM_MAX_RAM_PERCENTAGE} -Xss${MEM_XSS} -XX:+UseContainerSupport ${JVM_ARGS} -jar atbash-runtime.jar --logToConsole --deploymentdirectory ${DEPLOYMENT_DIR} ${ATBASH_ARGS}
----

=== Configuration file

When a configuration file is required to perform the setup of the runtime after booting up, copy the file with all the commands to the location `$CONFIG_FILE_LOCATION`.

[source]
----
COPY config.boot $CONFIG_FILE_LOCATION
----

=== Examples

Run a domain mode Runtime instance

[source,shell script]
----
docker run -d --name atbash -p 8080:8080 -e ATBASH_ARGS='--profile domain' runtime-main:0.3
----

Map a directory to the deployment directory so that it can run an application without assembling a specific Docker Image.

[source,shell script]
----
docker run -d --name atbash -p 8080:8080 -v "$PWD"/target:/opt/atbash/deployment runtime-main:0.3
----