== Logging

The Runtime controls the entire logging subsystem.

The configuration is performed through a properties file that configures the Java Util Logging system.  The file is expected at  `<instance>/logging.properties` and is created from a default when not found.

Within the Runtime itself, the logging is performed through SLF4J API.  A bridge to Java Util Logging is included.  The `be.atbash.runtime.logging.handler.LogFileHandler` handles the logging to file.

By default, no messages are written to the console and if needed, the `--logToConsole` is required to view logging entries also on the console.

=== Early logging

Since the logging module requires the Configuration module to be started (so that configuration is known) the logging cannot be configured immediately after the Java program starts. The initial logging is captured by an `EarlyLogHandler` that stores the LogRecords within memory until the logging module is ready.

The Early Logging is configured through this call:

[source]
----
LoggingManager.getInstance().initializeEarlyLogging(logToConsole);
----

Performed steps are

- Define _RuntimeLogManager_ as Log manager.
- Set logToConsole value as System property (`LoggingUtil.SYSTEM_PROPERTY_LOGGING_CONSOLE = "runtime.logging.console"`)
- Remove all handlers from the Root Logger.
- Add the Early Logging Handler.

When the Logging module has configured the Logging system (defined the logging properties), it _terminates_ the early logging. All messages stored in memory are written out to the loggers so they will appear in the logging file.

=== Important console logging

When specifying `--logToConsole` all logging also appears on the console when starting the Runtime.  Without this option, only a few important messages appears.

Any part of the code can write to the console by getting a special logger like this.

[source,java]
----
LoggingManager.getInstance().getMainLogger(xxx.class);
----

This will return a Logger that is properly setup forthe Console according the logToConsole option.