== Logging

The Runtime controls the entire logging subsystem.

The configuration is performed through a properties file that configures the Java Util Logging system.  The file is expected at  `<instance>/logging.properties` and is created from a default file when not found.

Within the Runtime itself, the logging is performed through SLF4J API.  A bridge to Java Util Logging is included.  The `be.atbash.runtime.logging.handler.LogFileHandler` handles the logging to file.

By default, only some important messages are written to the console and if needed, the `--logToConsole` is required to view logging entries also on the console.

=== Log format

Atbash Runtim comes included with 4 different log formats.  The default one is the SimpleLogFormat but the formatter can be changed by defining the fully qualified class name within the _logging.properties_ file.

[source]
----
be.atbash.runtime.logging.handler.LogFileHandler.formatter=be.atbash.runtime.logging.handler.formatter.SimpleLogFormatter
----

==== SimpleLogFormatter

The SimpleLogFormatter shows the basic information of the log records like this

[source]
----
Jun 11, 2022 22:33:45 be.atbash.runtime.MainRunnerHelper#logStartupTime INFO: CLI-103: Started Atbash Runtime in 0.882 secs
----

which corresponds to the following String format that is used by the logger.

[source]
----
%1$tb %1$td, %1$tY %1$tT %2$s %4$s: %5$s%6$s%n
----

parameter 1 -> Timestamp of the log entry
parameter 2 -> Name of the logger or the Class#Method name where the log entry is created.
parameter 3 -> Name of the logger (not shown in the default format)
parameter 4 -> Name of the log Level
parameter 5 -> Code of the log message
parameter 6 -> log message, includes the stacktrace in case the log entry is associated with a Throwable.

When you or the system, is making use of the Mapped Diagnostic Context (MDC) the entries are shown just before the actual message and can be configured by referencing parameter 7.

You can customise the output of the log format by the Simple Log formatter by defining the desired layout through the _log.properties_ file content

[source]
----
be.atbash.runtime.logging.handler.formatter.SimpleLogFormatter.format=%1$tb %1$td, %1$tY %1$tT %2$s %4$s: %5$s%6$s%n
be.atbash.runtime.logging.handler.formatter.SimpleLogFormatter.format.mdc=%1$tb %1$td, %1$tY %1$tT %2$s %4$s: [%7$s]%5$s%6$s%n
----

==== JSONLogger

Atbash Runtime has a JSON Log formatter included that can be selected by defining its fully qualified class name in the _logging.properties_ file for the formatter key.

[source]
----
be.atbash.runtime.logging.handler.LogFileHandler.formatter=be.atbash.runtime.logging.handler.formatter.JSONLogFormatter
----

The generated log entries looks like

[source]
----
{"Level":"INFO","LevelValue":"800","LogMessage":"CLI-103: Started Atbash Runtime in 1.152 secs","LoggerName":"be.atbash.runtime.RuntimeMain","MessageID":"CLI-103","ThreadID":"1","ThreadName":"main","TimeMillis":"1655060565219","Timestamp":"2022-06-12T21:02:45.219+0200"}
----

By default, following information is included

- The Log Level name and value
- The Log message
- The Message Id
- The Thread id and name where the log entry is generated
- The time information (as millis since 1 JAn 1970 and as String according to RFC3339)
- When an Exception is associated with the entry, an additional `Throwable` property key that is a Json Object structure containing the Exception message and the StackTrace
- Additional Json properties can be included for the MDC data.

When the Log Level is FINE or lower, the class and method name are included in the output.

Some properties can be excluded by defining it as an exclude field.

[source]
----
be.atbash.runtime.logging.handler.LogFileHandler.excludeFields=x,y,z
----

As indicated in the example, the keys needs to be separated by a `,` and the following keys are supported

- `tid`: no Thread Id and Thread name in the log entry
- `timeMillis`  The field _TimeMillis_  is omitted in the output.
- `levelValue`  The field _LevelValue_  is omitted in the output.

==== ODLLogger

==== Uniform Logger

Atbash Runtime has a Uniform Log formatter included based on te Glassfish and Payara products. It can be selected by defining its fully qualified class name in the _logging.properties_ file for the formatter key.

[source]
----
be.atbash.runtime.logging.handler.LogFileHandler.formatter=be.atbash.runtime.logging.handler.formatter.UniformLogFormatter
----

The generated log entries looks like

[source]
----
[#|2022-06-13T13:20:50.690+0200|INFO|be.atbash.runtime.RuntimeMain|_ThreadID=1;_ThreadName=main;_TimeMillis=1655119250690;_LevelValue=800;|CLI-103: Started Atbash Runtime in 0.984 secs|#]
----

Fields are seperated by `|` (but this can be configured) and there is one single field containing the optional fields and the MDC values.

By default, following information is included

- The Log Level name and value
- The Log message
- The Thread id and name where the log entry is generated
- The time information (as millis since 1 Jan 1970 and as String according to RFC3339)
- When an Exception is associated with the entry, the exception message and the Stacktrace is part of the log message.

When the Log Level is FINE or lower, the class and method name are included in the output (within the single field containing several log field entries).

Some values can be excluded by defining it as an exclude field.

[source]
----
be.atbash.runtime.logging.handler.LogFileHandler.excludeFields=x,y,z
----

As indicated in the example, the keys needs to be separated by a `,` and the following keys are supported

- `tid`: no Thread Id and Thread name in the log entry
- `timeMillis`  The field _TimeMillis_  is omitted in the output.
- `levelValue`  The field _LevelValue_  is omitted in the output.

The UniformLogger also supports colored output which is only useful for console output as the log entries otherwise contain some 'special' characters.

The activation can be done by having the following entry within _logging.properties_ file

[source]
----
be.atbash.runtime.logging.handler.formatter.UniformLogFormatter.ansiColor=true
----

=== Features

When the runtime starts, a rotation of the log file happens (if the instance has already a log file from the previous run).

The rotation of the log file is recommended (to avoid log files that become too large and can't be opened anymore)

There are several options for rotation.

. Size based: This is the default that is active.When the file becomes larger that the configured size (2 MB by default), a rotation happens.
. Daily: A rotation can be requested at the start of the day (based on the clock of the server running the process).
. Time based: A rotation every x minutes can be requested.

The size based option is combined with the time based options.So unless you disable the size based rotation, you might so rotation happening of the log file in between the time based one.

Time based rotation (including the daily one) has a granularity of 1 minute.So the rotation can happen at maximum 1 minute before or after the intended moment.

Daily rotation has precedence over the time based rotation.

=== SLF4J message format and Resource Bundle

The Atbash Runtime includes a special SLF4J to Java util Logging bridge.This bridge allows you to use Resource Bundles in combination with SLF4J.For a SLF4J logger, the corresponding ResourceBundle is looked up according to this mapping.

`LoggerFactory.getLogger(Foo.class);`  -> ResourceBundle is `msg.the.package.to.FOO.properties`.

When the message passed to the SLF4J logger contains the `{}` placeholder, the message formatting is performed according the SLF4J rules.
Otherwise the Java Util Logging formatter is responsible for creating the final message.

More functionality in the next phase of the Logger module rewrite.

== Logging - Technical

=== Early logging

Since the logging module requires the Configuration module to be started (so that configuration is known) the logging cannot be configured immediately after the Java program starts. The initial logging is captured by an `EarlyLogHandler` that stores the LogRecords within memory until the logging module is ready.

The Early Logging is configured through this call:

[source]
----
LoggingManager.getInstance().initializeEarlyLogging(logToConsole);
----

Performed steps are

- Define _RuntimeLogManager_ as Log manager.
- Set logToConsole value as System property (`LoggingUtil.SYSTEM_PROPERTY_LOGGING_CONSOLE = "runtime.logging.console"`)
- Remove all handlers from the Root Logger.
- Add the Early Logging Handler.

When the Logging module has configured the Logging system (defined the logging properties), it _terminates_ the early logging. All messages stored in memory are written out to the loggers so they will appear in the logging file.

=== Important console logging

When specifying `--logToConsole` all logging also appears on the console when starting the Runtime.  Without this option, only a few important messages appears.

Any part of the code can write to the console by getting a special logger like this.

[source,java]
----
LoggingManager.getInstance().getMainLogger(xxx.class);
----

This will return a Logger that is properly setup forthe Console according the logToConsole option.