== Logging

The Runtime controls the entire logging subsystem.

The configuration is performed through a properties file that configures the Java Util Logging system.  The file is expected at  `<instance>/logging.properties` and is created from a default file when not found.

Within the Runtime itself, the logging is performed through SLF4J API.  A bridge to Java Util Logging is included.  The `be.atbash.runtime.logging.handler.LogFileHandler` handles the logging to file.

By default, only some important messages are written to the console and if needed, the `--logToConsole` is required to view logging entries also on the console.

=== Features

When the runtime starts, a rotation of the log file happens (if the instance has already a log file from the previous run).

The rotation of the log file is recommended (to avoid log files that become too large and can't be opened anymore)

There are several options for rotation.

. Size based: This is the default that is active. When the file becomes larger that the configured size (2 MB by default), a rotation happens.
. Daily: A rotation can be requested at the start of the day (based on the clock of the server running the process).
. Time based: A rotation every x minutes can be requested.

The size based option is combined with the time based options. So unless you disable the size based rotation, you might so rotation happening of the log file in between the time based one.

Time based rotation (including the daily one) has a granularity of 1 minute. So the rotation can happen at macimum 1 minute before or after the intended moment.

Daily rotation has precedence over the time based rotation.




== Logging - Technical

=== Early logging

Since the logging module requires the Configuration module to be started (so that configuration is known) the logging cannot be configured immediately after the Java program starts. The initial logging is captured by an `EarlyLogHandler` that stores the LogRecords within memory until the logging module is ready.

The Early Logging is configured through this call:

[source]
----
LoggingManager.getInstance().initializeEarlyLogging(logToConsole);
----

Performed steps are

- Define _RuntimeLogManager_ as Log manager.
- Set logToConsole value as System property (`LoggingUtil.SYSTEM_PROPERTY_LOGGING_CONSOLE = "runtime.logging.console"`)
- Remove all handlers from the Root Logger.
- Add the Early Logging Handler.

When the Logging module has configured the Logging system (defined the logging properties), it _terminates_ the early logging. All messages stored in memory are written out to the loggers so they will appear in the logging file.

=== Important console logging

When specifying `--logToConsole` all logging also appears on the console when starting the Runtime.  Without this option, only a few important messages appears.

Any part of the code can write to the console by getting a special logger like this.

[source,java]
----
LoggingManager.getInstance().getMainLogger(xxx.class);
----

This will return a Logger that is properly setup forthe Console according the logToConsole option.