== Messages

Messages with a code number greater than 1000 are informational messages that are show in the log with the _verbose_ option.  +
Values smaller than 1000 indicate some info, warning or error that is important for the operations of the environment.

=== Core module

- DEPLOY-101(INFO): Start of the Deployment of the application.
- DEPLOY-102(INFO): End of the Deployment of the application.
- DEPLOY-103(WARNING): The archive cannot be found. +
When starting the Runtime and previously installed applications are started.
- DEPLOY-104(WARNING): The archive could not be inspected  +
When deploying the application but the war file corrupt or the contents of the war file is empty.
- DEPLOY-105(WARNING): The archive cannot be found.
When passing a file name on the command line.
- DEPLOY-106(WARNING): The archive file does not have the extension `.war`.

=== Config module

- CONFIG-011(ERROR): Incorrect profile name specified.
- CONFIG-012(ERROR): Incorrect module name specified.
- CONFIG-013(ERROR): Unable to parse the content of a configuration file. (file is indicated in the error message)
- CONFIG-014(ERROR): The directory specified in the --root option does not exists.
- CONFIG-015(ERROR): The directory specified in the --root option is not a directory.
- CONFIG-016(ERROR): Cannot create the directory for the 'domain' (configuration, logs, ...).
- CONFIG-017(ERROR): The directory for the 'domain' (configuration, logs, ...) already exists and is not allowed for the Runtime CLI tool.
- CONFIG-018(WARN): The file _applications.json_  cannot be written. This means that the application will not start the next time

- CONFIG-101(ERROR): The option specified for the _set_ command must consist of <key>=<value> pairs separated by a space.
- CONFIG-102(ERROR): The key part of the option specified for the _set_ command must be in the format <module>.<key-parts>
- CONFIG-103(ERROR): The line _n_ in the configuration file could not be recognized as a valid command with parameters.
- CONFIG-104(INFO): Processing of the command on line _n_ within the configuration file failed.

=== Logging Module

=== Jetty module

=== Jersey module

