=== Atbash Jakarta Runner mode

The Atbash Runtime can also be used to run your Jakarta EE Core Profile application from the main method.  In this case, you do not create a WAR file, but specify the JAX-RS application or JAX-RS resources to the Runner methods within your Java SE main method.


=== Dependency

Add the following Maven dependency to your project

[source,xml]
----
        <dependency>
            <groupId>be.atbash.runtime</groupId>
            <artifactId>jakarta-executable</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>be.atbash.runtime</groupId>
            <artifactId>jakarta-executable-impl</artifactId>
            <version>1.0.0-SNAPSHOT</version>
            <!-- only needed at runtime, but since jar packaging, you cannot specify its scope. -->
        </dependency>
----

=== Define Configuration

There is a Runner Builder available to define the configuration.

[source,java]
----
    JakartaSERunnerBuilder.newBuilder(DemoApplication.class)
        .run();
----

You can either specify a class that extends the JAX-RS Application class or a list of JAX-RS resource classes.

When using the JAX-RS Application class, either the JAX-RS resources are retrieved from the `getClasses()` method (from that _Application_ class) or the class path is scanned for JAX-RS resources within the package (and subpackages) of that class.

When using the Application class way, the `@ApplicationPath` is honored. If you create a new Jakarta Runner builder by specifying a list of JAX-RS resource classes, this value, if present, is ignored.

The builder has additional methods to configure the runner.

[source,java]
----
    .addPort(int)
----

Specifies the port assignment for the socket listener.

[source,java]
----
    .addConfig(String key, String value)
----

Defines configuration values, for the application Deployer module or for the special `ConfigSource` implementation that these values exposes.  See ???

=== Active Modules

By default, the `jakarta-executable-impl` dependency activates the JAX_RS, CDI, JSON-B, JSON-P and MicroProfile Config functionality.

The general rule for the Runner mode is that when a Atbash Runtime module is on the classpath, it is active. You can deactivate a module, like MP Config, by specifying a certain property. Have a look at the modules on how to do this.

=== Known issues
