=== Atbash Jakarta Runner mode

The Atbash Runtime can also be used to run your Jakarta EE Core Profile application from the main method.  In this case, you do not create a WAR file, but specify the JAX-RS application or JAX-RS resources to the Runner methods within your Java SE main method.


=== Dependency

Add the following Maven dependency to your project

[source,xml]
----
        <dependency>
            <groupId>be.atbash.runtime</groupId>
            <artifactId>jakarta-executable</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>be.atbash.runtime</groupId>
            <artifactId>jakarta-executable-impl</artifactId>
            <version>1.0.0-SNAPSHOT</version>
            <!-- only needed at runtime, but since jar packaging, you cannot specify its scope. -->
        </dependency>
----

=== Define Configuration

There is a Runner Builder available to define the configuration.

[source,java]
----
    JakartaSERunnerBuilder.newBuilder(DemoApplication.class)
        .run();
----

You can either specify a class that extends the JAX-RS Application class or a list of JAX-RS resource classes.

When using the JAX-RS Application class, either the JAX-RS resources are retrieved from the `getClasses()` method (from that _Application_ class) or the class path is scanned for JAX-RS resources within the package (and subpackages) of that class.

When using the Application class way, the `@ApplicationPath` is honored. If you create a new Jakarta Runner builder by specifying a list of JAX-RS resource classes, this value, if present, is ignored.

The builder has additional methods to configure the runner.

[source,java]
----
    .addPort(int)
----

Specifies the port assignment for the socket listener.

When your application wants to make use of additional modules, on top of the functionality provided by the Core Profile specifications, you can follow these steps.

. Add the module to your project, for example to have MicroProfile JWT support
[source,xml]
----
<dependency>
   <groupId>be.atbash.runtime</groupId>
   <artifactId>jwt-auth-module</artifactId>
   <version>1.0.0-SNAPSHOT</version>
</dependency>
----
. Add the name as required module to the runner configuration, for example
[source,java]
----
   .additionalModules(JWTAuthModule.JWT_AUTH_MODULE_NAME)
----

This pattern can be used add any module to the Jakarta Runner.

[source,java]
----
    .addConfig(String key, String value)
----

Defines configuration values, for the application Deployer module or for the special `ConfigSource` implementation that these values exposes.  See ???

[source,java]
----
    .addCommandLineEntry(String entry)
----

Defines an option for the configuration of the runner (corresponds with the command line parameters of the class Atbash Runtime). The following options are supported:

*-v|--verbose*: When active, more messages are shown in the log.  This can be enforced 'permanent' by putting `be.atbash.runtime.level=ALL` in the logging configuration.

*-w|--watcher*:  Defines the type of the diagnostics, valid values are  +
`MINIMAL`: (default) only the events from the Core module are sent to JFR.  +
`OFF`: JFR and JMX are disabled  +
`JFR`: Events are send to JFR system and Recording is started which is dump to file at JVM exit.  +
`JMX`: Some data is available within the JMX system.  +
`ALL`: Combination of `JFR` and `JMX`

*--logConfiguration <file>*: Define the location of the configuration file and activates the Log to file option.

*--warmup*: When this option is specified, the process exits after the application is deployed. This is typically used in combination with the Class Data Sharing option of the JVM to create archive file.

*--datafile*: Defines the configuration data properties file with key values pairs for the application(s) deployment data. These deployment data can influence the configuration of the modules. For an overview, see ??? ( FIXME create such a section)

=== Active Modules

By default, the `jakarta-executable-impl` dependency activates the JAX_RS, CDI, JSON-B, JSON-P and MicroProfile Config functionality.

The general rule for the Runner mode is that when a Atbash Runtime module is on the classpath, it is active. You can deactivate a module, like MP Config, by specifying a certain property. Have a look at the modules on how to do this.

=== Known issues
