= Runtime

A Jakarta EE 10 Core profile runtime.

== General

The product has several ways of operation

- standalone; Start up the runtime with one or more applications.
- domain; Start up the runtime and remotely administer the environment.
- clustered; Remote administration of several instances all running the same applications(s)
- embedded; Start the runtime as part of your application or test.

Applications are internally identified by the contextroot they are available (must be unique on the runtime) and when performing remote administration, applications are indicated by their deployment name.

== Known issues

- In order to have CDI injection in a JAX-RS resource to be working, the JAX-RS resource requires a CDI scope annotation.

== Installation

Unzip the _atbash-runtime.zip_ file to a location of your choice. The archive contains an executable JAR file in the root and the dependencies in the _lib_ folder.

From within the root folder, execute the command

[source]
----
java -jar atbash_runtime.jar <options>
----

(It is not possible to create a shaded executable jar file since that would make the entire code base a Bean Defining Archive in terms of CDI and will results in errors)

include::modules.adoc[]

include::logging.adoc[]

include::logging-config.adoc[]

include::commandlineoptions.adoc[]

include::mpconfig.adoc[]

include::mpjwt.adoc[]

include::microstream.adoc[]

include::bom.adoc[]

include::packager.adoc[]

include::runner.adoc[]

include::integrations.adoc[]

include::docker.adoc[]

include::testing.adoc[]

include::embedded.adoc[]

include::arquillian.adoc[]

include::domain-api.adoc[]

include::messages.adoc[]

include::expert.adoc[]